default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: rubymon_development

test:
  <<: *default
  database: rubymon_test

production:
  <<: *default
  database: rubymon_production
